name: torch-frcnn
channels:
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - numpy=1.20.3
  - pip
  - pandas=1.3.5
  - matplotlib
  - cython
  - pip:
    - transformers
    - torchsummary
    - albumentations
    - opencv-python
    - tensorboard
    - torchsummary
    - fiftyone
    - "git+https://github.com/openai/CLIP.git"
    - ftfy
    - regex
    - tqdm
    - jupyter
    - ipykernel
    - "git+https://github.com/bcperry/cocoapi_windows.git#subdirectory=PythonAPI"